// ── AI debrief facilitator — server route (runs on the Cloudflare Worker) ─────
// POST an anonymized game state; get back a short andakt + 2-3 discussion
// questions generated by Claude, grounded in Matt 13:24-30. The API key is a
// Worker secret (ANTHROPIC_API_KEY), read server-side only — never shipped to
// the client. Keyless → { available:false, reason:'no_key' } and the EndScreen
// keeps its existing static debrief (no regression). The model only SUGGESTS:
// output is sanitized against a strict shape before it leaves this route.

import { NextRequest, NextResponse } from 'next/server'
import { getLlmClient, type DebriefEnv } from '@/lib/debrief/llm'
import { buildDebriefRequest } from '@/lib/debrief/buildPrompt'
import { parseDebriefResponse } from '@/lib/debrief/parseResponse'
import { validateDebriefRequest } from '@/lib/debrief/validateRequest'
import type { DebriefResponse } from '@/lib/debrief/types'

export const runtime = 'nodejs'
// State-bearing: never let a CDN cache a generated debrief.
export const dynamic = 'force-dynamic'

async function readEnv(): Promise<DebriefEnv> {
  // On Cloudflare the secret arrives via the Worker env binding; in plain Node
  // dev it falls back to process.env. getCloudflareContext is imported lazily
  // so a non-CF runtime (e.g. the test gate) never needs the adapter.
  try {
    const { getCloudflareContext } = await import('@opennextjs/cloudflare')
    const { env } = getCloudflareContext()
    return env as unknown as DebriefEnv
  } catch {
    return { ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY }
  }
}

export async function POST(request: NextRequest) {
  const env = await readEnv()
  const client = getLlmClient(env)

  // No key configured → tell the client to keep the static fallback.
  if (!client) {
    return NextResponse.json<DebriefResponse>({
      available: false,
      reason: 'no_key',
    })
  }

  let body: unknown
  try {
    body = await request.json()
  } catch {
    body = null
  }

  const parsed = validateDebriefRequest(body)
  if (!parsed) {
    return NextResponse.json<DebriefResponse>(
      { available: false, reason: 'invalid' },
      { status: 400 }
    )
  }

  const reqBody = buildDebriefRequest(parsed.game, parsed.variant)
  const raw = await client.send(reqBody)
  const content = parseDebriefResponse(raw)

  if (!content) {
    return NextResponse.json<DebriefResponse>({
      available: false,
      reason: 'upstream_error',
    })
  }

  return NextResponse.json<DebriefResponse>({ available: true, content })
}
